#!/bin/bash

_docker_image=${PWD##*/}

if [ -d "/dev/dri" ]; then
  _args="--device /dev/dri:/dev/dri -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -e HAS_GPU=1"
  if [ -d "/usr/lib/wsl" ]; then
    _args+=" --device /dev/dxg:/dev/dxg -v /usr/lib/wsl:/usr/lib/wsl"
  fi
fi

if [ -d "/dev/accel" ]; then
  _args+=" --device /dev/accel:/dev/accel -e HAS_NPU=1"
fi

docker run -it --rm --security-opt seccomp=unconfined -v `pwd`:/project -w /project $_args $_docker_image $@
